In [21]:
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F

In [22]:
df = pd.read_csv("BostonHousing.csv")
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [23]:
x = df.drop('medv', axis=1)
y = df['medv']

In [24]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [25]:
x = x.values

In [26]:
y = y.values

In [27]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [28]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [29]:
x.shape

(506, 13)

In [30]:
x_train = x[0:405, :]
x_test = x[406::, :]

In [31]:
x_train.shape, x_test.shape

((405, 13), (100, 13))

In [32]:
y.shape

(506,)

In [33]:
y_train = y[0:405]
y_test = y[406::]

In [34]:
y_train.shape, y_test.shape

((405,), (100,))

In [35]:
x_test = torch.FloatTensor(x_test)
x_train = torch.FloatTensor(x_train)
y_test = torch.FloatTensor(y_test)
y_train = torch.FloatTensor(y_train)

In [60]:
class LinearRegressionModel(nn.Module):
    def __init__(self, in_features = 13, out_features=1):
        super().__init__()
        self.func = nn.Linear(in_features, out_features)

    def forward(self, x):
        out = self.func(x)

        return out

In [61]:
model = LinearRegressionModel()

In [62]:
model.parameters()

<generator object Module.parameters at 0x0000014246C91E00>

In [63]:
loss_func = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

In [71]:
epochs = 1000
losses = []

for epoch in range(epochs):
    y_pred = model.forward(x_train)
    loss = loss_func(y_pred, y_train)

    losses.append(loss.detach())

    if epoch%10 == 0:
        print(f"Epoch: {epoch}, loss: {loss}")

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

C:\Users\IMCK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([405])) that is different to the input size (torch.Size([405, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch: 0, loss: 87.9283218383789
Epoch: 10, loss: 87.9171371459961
Epoch: 20, loss: 87.9061050415039
Epoch: 30, loss: 87.89522552490234
Epoch: 40, loss: 87.88449096679688
Epoch: 50, loss: 87.87391662597656
Epoch: 60, loss: 87.86347198486328
Epoch: 70, loss: 87.8531723022461
Epoch: 80, loss: 87.84300231933594
Epoch: 90, loss: 87.83297729492188
Epoch: 100, loss: 87.82307434082031
Epoch: 110, loss: 87.81330108642578
Epoch: 120, loss: 87.80364990234375
Epoch: 130, loss: 87.79412078857422
Epoch: 140, loss: 87.78471374511719
Epoch: 150, loss: 87.77542877197266
Epoch: 160, loss: 87.7662582397461
Epoch: 170, loss: 87.7572021484375
Epoch: 180, loss: 87.74825286865234
Epoch: 190, loss: 87.73941040039062
Epoch: 200, loss: 87.73067474365234
Epoch: 210, loss: 87.7220458984375
Epoch: 220, loss: 87.71351623535156
Epoch: 230, loss: 87.70509338378906
Epoch: 240, loss: 87.69676208496094
Epoch: 250, loss: 87.68853759765625
Epoch: 260, loss: 87.68038940429688
Epoch: 270, loss: 87.67234802246094
Epoch: 280

In [65]:
y_pred.shape, y_train.shape

(torch.Size([405, 1]), torch.Size([405]))

In [66]:
print(losses)

[tensor(2432.9368), tensor(1673.5062), tensor(1076.6844), tensor(641.6796), tensor(361.8499), tensor(222.0559), tensor(196.5935), tensor(249.7639), tensor(340.7998), tensor(432.1109), tensor(496.8461), tensor(522.0859), tensor(507.3278), tensor(460.5091), tensor(393.8173), tensor(320.3512), tensor(251.7942), tensor(196.9268), tensor(160.8052), tensor(144.5305), tensor(145.5994), tensor(158.8080), tensor(177.5783), tensor(195.4353), tensor(207.2957), tensor(210.2798), tensor(203.9236), tensor(189.8500), tensor(171.0737), tensor(151.1566), tensor(133.3998), tensor(120.2129), tensor(112.7482), tensor(110.8348), tensor(113.1961), tensor(117.8779), tensor(122.7746), tensor(126.1228), tensor(126.8491), tensor(124.7078), tensor(120.2069), tensor(114.3679), tensor(108.4038), tensor(103.3993), tensor(100.0680), tensor(98.6336), tensor(98.8454), tensor(100.1097), tensor(101.6878), tensor(102.9034), tensor(103.3049), tensor(102.7449), tensor(101.3698), tensor(99.5330), tensor(97.6674), tensor(96.

In [73]:
with torch.no_grad():
    y_eval = model.forward(x_test)
    loss = loss_func(y_eval, y_test)
    print(loss)
    for i in range(len(y_eval)):
        print(f"y_eval: {y_eval[i].item()}, y_test: {y_test[i]}, diff: {y_eval[i].item() - y_test[i]}.")

tensor(81.7157)
y_eval: 22.753387451171875, y_test: 11.899999618530273, diff: 10.853387832641602.
y_eval: 23.226465225219727, y_test: 27.899999618530273, diff: -4.673534393310547.
y_eval: 23.258209228515625, y_test: 17.200000762939453, diff: 6.058208465576172.
y_eval: 23.042287826538086, y_test: 27.5, diff: -4.457712173461914.
y_eval: 20.74976348876953, y_test: 15.0, diff: 5.749763488769531.
y_eval: 22.147016525268555, y_test: 17.200000762939453, diff: 4.947015762329102.
y_eval: 21.159038543701172, y_test: 17.899999618530273, diff: 3.2590389251708984.
y_eval: 22.034475326538086, y_test: 16.299999237060547, diff: 5.734476089477539.
y_eval: 21.974895477294922, y_test: 7.0, diff: 14.974895477294922.
y_eval: 22.760643005371094, y_test: 7.199999809265137, diff: 15.560643196105957.
y_eval: 22.933387756347656, y_test: 7.5, diff: 15.433387756347656.
y_eval: 22.463497161865234, y_test: 10.399999618530273, diff: 12.063497543334961.
y_eval: 21.75163459777832, y_test: 8.800000190734863, diff: 12.9

In [68]:
model.state_dict()

OrderedDict([('func.weight',
              tensor([[-0.0195,  0.0020,  0.0529,  0.2897,  0.5301,  0.5965,  0.0214,  0.3540,
                       -0.1513,  0.0087,  0.1723,  0.0282,  0.0333]])),
             ('func.bias', tensor([0.3457]))])

In [69]:
# torch.save(model.state_dict(), "housePrice.pt")